apiVersion: apps/v1
kind: Deployment
metadata:
 name: order
 namespace: order
spec:
 replicas: 2
 selector:
   matchLabels:
     app: order
     version: v1
 template:
   metadata:
     labels:
       app: order
       version: v1
   spec:
     containers:
     - name: order
       image: hashicorp/http-echo
       args:
         - -listen=:8080
         - -text="Order Service"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  name: order-svc
  namespace: order
spec:
 ports:
 - name: service
   port: 8080
   protocol: TCP
 selector:
   app: order
   version: v1
 type: ClusterIP